//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-1.0.0.0_2-1-9-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.08 at 09:49:15 AM EST 
//


package dti.ci.entitymgr.impl.jdbchelpers;

import com.delphi_tech.ows.party.*;
import oracle.sql.ARRAY;
import oracle.sql.Datum;
import oracle.sql.STRUCT;

import javax.xml.bind.annotation.*;
import java.sql.*;


public class AddressType implements SQLData {

    protected String addressNumberId;
    protected String externalReferenceId;
    protected String lineOne;
    protected String lineTwo;
    protected String lineThree;
    protected String cityName;
    protected String countyCode;
    protected String postalCode;
    protected String countryName;
    protected String attentionName;
    protected String key;

    protected StateOrProvinceCodeType stateOrProvinceCode;
    protected CountryCodeType countryCode;
    protected PostOfficeAddressIndicatorType postOfficeAddressIndicator;
    protected String municipalCode;

    protected  com.delphi_tech.ows.party.AddressType jaxbAddressType;
    
     public String sql_type="ADDRESSTYPE";

     public String getSQLTypeName() throws SQLException {
           return sql_type;
     }
    public com.delphi_tech.ows.party.AddressType getJaxbAddressType(){
        return jaxbAddressType;
    }
    public AddressType(String addressNumberId, String externalReferenceId, String lineOne,String lineTwo, String lineThree,
                      String cityName,String countyCode,StateOrProvinceCodeType stateOrProvinceCode,
                      String postalCode,CountryCodeType countryCode,
                      String countryName, String attentionName,
                      PostOfficeAddressIndicatorType postOfficeAddressIndicator, String municipalCode, String key)
    {
        this.addressNumberId = addressNumberId;
        this.externalReferenceId = externalReferenceId;
        this.lineOne = lineOne;
        this.lineTwo = lineTwo;
        this.lineThree = lineThree;
        this.cityName = cityName;
        this.countyCode = countyCode;
        this.postalCode = postalCode;
        this.countryName = countryName;
        this.attentionName = attentionName;
        this.key = key;
        this.stateOrProvinceCode = stateOrProvinceCode;
        this.countryCode = countryCode;
        this.postOfficeAddressIndicator = postOfficeAddressIndicator;
        this.municipalCode = municipalCode;

        jaxbAddressType = new   com.delphi_tech.ows.party.AddressType();
        jaxbAddressType.setAddressNumberId(this.addressNumberId);
        jaxbAddressType.setExternalReferenceId(this.externalReferenceId);
        jaxbAddressType.setLineOne(this.lineOne);
        jaxbAddressType.setLineTwo(this.lineTwo);
        jaxbAddressType.setLineThree(this.lineThree);
        jaxbAddressType.setCityName(this.cityName);
        jaxbAddressType.setCountyCode(this.countyCode);
        jaxbAddressType.setAttentionName(this.attentionName);
        jaxbAddressType.setKey(this.key);
        jaxbAddressType.setStateOrProvinceCode(this.stateOrProvinceCode.getJaxbStateOrProvinceCodeType());
        jaxbAddressType.setCountryCode(this.countryCode.getJaxbCountryCodeType());
        jaxbAddressType.setPostOfficeAddressIndicator(this.postOfficeAddressIndicator.getJaxbPostOfficeAddressIndicatorType());
        jaxbAddressType.setMunicipalCode(this.municipalCode);
    }

         public void readSQL(SQLInput stream,String typeName ) throws SQLException{
         sql_type = typeName;
         addressNumberId = stream.readString();
         externalReferenceId = stream.readString();
         lineOne = stream.readString();
         lineTwo = stream.readString();
         lineThree = stream.readString();
         cityName = stream.readString();
         countyCode = stream.readString();
         postalCode = stream.readString();
         countryName = stream.readString();
         attentionName = stream.readString();
         key = stream.readString();
         stateOrProvinceCode   = (StateOrProvinceCodeType)setClass(stream.readObject(),StateOrProvinceCodeType.class );
         countryCode = (CountryCodeType) setClass(stream.readObject(), CountryCodeType.class);
         postOfficeAddressIndicator = (PostOfficeAddressIndicatorType)setClass(stream.readObject(), PostOfficeAddressIndicatorType.class);
         municipalCode = stream.readString();
             jaxbAddressType = new   com.delphi_tech.ows.party.AddressType();
             jaxbAddressType.setAddressNumberId((this.addressNumberId));
             jaxbAddressType.setExternalReferenceId(this.externalReferenceId == null ? "" : externalReferenceId);
             jaxbAddressType.setLineOne((this.lineOne==null)?"":lineOne);
             jaxbAddressType.setLineTwo((this.lineTwo==null)?"":lineTwo);
             jaxbAddressType.setLineThree((this.lineThree==null)?"":lineThree);
             jaxbAddressType.setCityName((this.cityName==null)?"":cityName);
             jaxbAddressType.setCountyCode((this.countyCode == null)?"":countyCode);
             jaxbAddressType.setAttentionName((this.attentionName == null)?"":attentionName);
             jaxbAddressType.setKey(this.key);
             jaxbAddressType.setPostalCode((this.postalCode==null)?"":this.postalCode);
             
             if(stateOrProvinceCode != null){
                 jaxbAddressType.setStateOrProvinceCode(this.stateOrProvinceCode.getJaxbStateOrProvinceCodeType());
              }else{
                   jaxbAddressType.setStateOrProvinceCode(  new com.delphi_tech.ows.party.StateOrProvinceCodeType() ) ;
              }

             if(countryCode != null){
                jaxbAddressType.setCountryCode(this.countryCode.getJaxbCountryCodeType());
             }else{
                  jaxbAddressType.setCountryCode(  new com.delphi_tech.ows.party.CountryCodeType() ) ;
             }
             if(postOfficeAddressIndicator != null){
                jaxbAddressType.setPostOfficeAddressIndicator(this.postOfficeAddressIndicator.getJaxbPostOfficeAddressIndicatorType());
             }else{
                jaxbAddressType.setPostOfficeAddressIndicator( new com.delphi_tech.ows.party.PostOfficeAddressIndicatorType());
             }
             jaxbAddressType.setMunicipalCode((this.municipalCode==null)?"":this.municipalCode);
     }
    public void writeSQL(SQLOutput stream) throws SQLException{
        /*
            This method should not have implementation
            We are not planning to make any updates using this method.
        */
     }

    private  Object setClass(Object obj, Class clazz){
        Object type=null;
       try{
        ARRAY tmp = (ARRAY)obj;
        ResultSet rs = tmp.getResultSet();
         while(rs.next()){
               STRUCT struct = (STRUCT) rs.getObject(2);
               type = struct.toClass(clazz);
           }
       }catch(Exception e){
           //do nothing  just return null
           e.getMessage();
       }
     return type;   
    }


    public AddressType(){}
    /**
     * Gets the value of the addressNumberId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAddressNumberId() {
        return addressNumberId;
    }

    /**
     * Sets the value of the addressNumberId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAddressNumberId(String value) {
        this.addressNumberId = value;
    }

    /**
     * Gets the value of the lineOne property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLineOne() {
        return lineOne;
    }

    /**
     * Sets the value of the lineOne property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLineOne(String value) {
        this.lineOne = value;
    }

    /**
     * Gets the value of the lineTwo property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLineTwo() {
        return lineTwo;
    }

    /**
     * Sets the value of the lineTwo property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLineTwo(String value) {
        this.lineTwo = value;
    }

    /**
     * Gets the value of the lineThree property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLineThree() {
        return lineThree;
    }

    /**
     * Sets the value of the lineThree property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLineThree(String value) {
        this.lineThree = value;
    }

    /**
     * Gets the value of the cityName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * Sets the value of the cityName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCityName(String value) {
        this.cityName = value;
    }

    /**
     * Gets the value of the countyCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCountyCode() {
        return countyCode;
    }

    /**
     * Sets the value of the countyCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCountyName(String value) {
        this.countyCode = value;
    }

    /**
     * Gets the value of the stateOrProvinceCode property.
     *
     * @return
     *     possible object is
     *     {@link dti.ci.entitymgr.impl.jdbchelpers.StateOrProvinceCodeType }
     *
     */
    public StateOrProvinceCodeType getStateOrProvinceCode() {
        return stateOrProvinceCode;
    }

    /**
     * Sets the value of the stateOrProvinceCode property.
     *
     * @param value
     *     allowed object is
     *     {@link dti.ci.entitymgr.impl.jdbchelpers.StateOrProvinceCodeType }
     *
     */
    public void setStateOrProvinceCode(StateOrProvinceCodeType value) {
        this.stateOrProvinceCode = value;
    }

    /**
     * Gets the value of the postalCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the countryCode property.
     *
     * @return
     *     possible object is
     *     {@link CountryCodeType }
     *
     */
    public CountryCodeType getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     *
     * @param value
     *     allowed object is
     *     {@link CountryCodeType }
     *
     */
    public void setCountryCode(CountryCodeType value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the countryName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * Sets the value of the countryName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCountryName(String value) {
        this.countryName = value;
    }

    /**
     * Gets the value of the attentionName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAttentionName() {
        return attentionName;
    }

    /**
     * Sets the value of the attentionName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAttentionName(String value) {
        this.attentionName = value;
    }

    /**
     * Gets the value of the postOfficeAddressIndicator property.
     *
     * @return
     *     possible object is
     *     {@link dti.ci.entitymgr.impl.jdbchelpers.PostOfficeAddressIndicatorType }
     *
     */
    public PostOfficeAddressIndicatorType getPostOfficeAddressIndicator() {
        return postOfficeAddressIndicator;
    }

    /**
     * Sets the value of the postOfficeAddressIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link dti.ci.entitymgr.impl.jdbchelpers.PostOfficeAddressIndicatorType }
     *
     */
    public void setPostOfficeAddressIndicator(PostOfficeAddressIndicatorType value) {
        this.postOfficeAddressIndicator = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKey(String value) {
        this.key = value;
    }

    public String getExternalReferenceId() {
        return externalReferenceId;
    }

    public void setExternalReferenceId(String externalReferenceId) {
        this.externalReferenceId = externalReferenceId;
    }
}