//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-1.0.0.0_2-1-9-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.08 at 09:49:15 AM EST 
//


package dti.ci.entitymgr.impl.jdbchelpers;

import oracle.sql.ARRAY;
import oracle.sql.STRUCT;

import java.sql.*;


public class
        BasicPhoneNumberType implements SQLData {

    protected String phoneNumberId;
    protected PhoneTypeCodeType phoneTypeCode;
    protected String phoneNumber;
    protected PrimaryIndicatorType primaryIndicator;
    protected String addressReference;
    protected String key;

    protected com.delphi_tech.ows.party.BasicPhoneNumberType jaxbBasicPhoneNumberType;

     public String sql_type;

     public String getSQLTypeName() throws SQLException {
           return sql_type;
     }

    public BasicPhoneNumberType(){
        jaxbBasicPhoneNumberType = new com.delphi_tech.ows.party.BasicPhoneNumberType();
    }

    public BasicPhoneNumberType(String phoneNumberId,PhoneTypeCodeType phoneTypeCode,String phoneNumber,
                                 PrimaryIndicatorType primaryIndicator,
                                 String addressReference,
                                 String key){
      this.phoneNumberId = phoneNumberId;
      this.phoneTypeCode = phoneTypeCode;
      this.phoneNumber = phoneNumber;
      this.primaryIndicator = primaryIndicator;
      this.addressReference = addressReference;
      this.key = key;

        jaxbBasicPhoneNumberType = new com.delphi_tech.ows.party.BasicPhoneNumberType();
        jaxbBasicPhoneNumberType.setPhoneNumberId(this.phoneNumberId);
       if(phoneTypeCode != null){
        jaxbBasicPhoneNumberType.setPhoneTypeCode(this.phoneTypeCode.getJaxbPhoneTypeCodeType());
       }else{
           jaxbBasicPhoneNumberType.setPhoneTypeCode(new  com.delphi_tech.ows.party.PhoneTypeCodeType());
       }
       jaxbBasicPhoneNumberType.setPhoneNumber(this.phoneNumber);
        if(primaryIndicator != null){
            jaxbBasicPhoneNumberType.setPrimaryIndicator(this.primaryIndicator.getJaxbPrimaryIndicatorType());
        }else{
           jaxbBasicPhoneNumberType.setPrimaryIndicator( new com.delphi_tech.ows.party.PrimaryIndicatorType());
        }
       jaxbBasicPhoneNumberType.setAddressReference(this.addressReference);
        if(key != null ){
            jaxbBasicPhoneNumberType.setKey(this.key);
        }
    }


     public void readSQL(SQLInput stream,String typeName ) throws SQLException{
         sql_type = typeName;
         phoneNumberId = stream.readString();
         phoneTypeCode =  (PhoneTypeCodeType) setClass(stream.readObject(),PhoneTypeCodeType.class);
         phoneNumber = stream.readString();
         primaryIndicator = (PrimaryIndicatorType) setClass(stream.readObject(),PrimaryIndicatorType.class);
         addressReference = stream.readString();
         key = stream.readString();

       jaxbBasicPhoneNumberType.setPhoneNumberId((this.phoneNumberId==null)?"":phoneNumberId);
       if(phoneTypeCode != null){
        jaxbBasicPhoneNumberType.setPhoneTypeCode(this.phoneTypeCode.getJaxbPhoneTypeCodeType());
       }else{
           jaxbBasicPhoneNumberType.setPhoneTypeCode(new  com.delphi_tech.ows.party.PhoneTypeCodeType());
       }
       jaxbBasicPhoneNumberType.setPhoneNumber(this.phoneNumber);
        if(primaryIndicator != null){
            jaxbBasicPhoneNumberType.setPrimaryIndicator(this.primaryIndicator.getJaxbPrimaryIndicatorType());
        }else{
           jaxbBasicPhoneNumberType.setPrimaryIndicator( new com.delphi_tech.ows.party.PrimaryIndicatorType());
        }
         // If address reference is null, the attribute will not be displayed.
       jaxbBasicPhoneNumberType.setAddressReference(addressReference);
       jaxbBasicPhoneNumberType.setKey((this.key == null) ? "":key);

     }

    public com.delphi_tech.ows.party.BasicPhoneNumberType getJaxbBasicPhoneNumberType(){
        return this.jaxbBasicPhoneNumberType;
    }
    public void writeSQL(SQLOutput stream) throws SQLException{
        /*
            This method should not have implementation
            We are not planning to make any updates using this method.
        */
     }

    private  Object setClass(Object obj, Class clazz){
        Object type=null;
       try{
        ARRAY tmp = (ARRAY)obj;
        ResultSet rs = tmp.getResultSet();
         while(rs.next()){
               STRUCT struct = (STRUCT) rs.getObject(2);
               type = struct.toClass(clazz);
           }
       }catch(Exception e){
           //do nothing  just return null
           e.getMessage();
       }
     return type;
    }


    /**
     * Gets the value of the phoneNumberId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPhoneNumberId() {
        return phoneNumberId;
    }

    /**
     * Sets the value of the phoneNumberId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPhoneNumberId(String value) {
        this.phoneNumberId = value;
    }

    /**
     * Gets the value of the phoneTypeCode property.
     *
     * @return
     *     possible object is
     *     {@link PhoneTypeCodeType }
     *
     */
    public PhoneTypeCodeType getPhoneTypeCode() {
        return phoneTypeCode;
    }

    /**
     * Sets the value of the phoneTypeCode property.
     *
     * @param value
     *     allowed object is
     *     {@link PhoneTypeCodeType }
     *
     */
    public void setPhoneTypeCode(PhoneTypeCodeType value) {
        this.phoneTypeCode = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the primaryIndicator property.
     *
     * @return
     *     possible object is
     *     {@link PrimaryIndicatorType }
     *
     */
    public PrimaryIndicatorType getPrimaryIndicator() {
        return primaryIndicator;
    }

    /**
     * Sets the value of the primaryIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link PrimaryIndicatorType }
     *
     */
    public void setPrimaryIndicator(PrimaryIndicatorType value) {
        this.primaryIndicator = value;
    }

    /**
     * Gets the value of the addressReference property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAddressReference() {
        return addressReference;
    }

    /**
     * Sets the value of the addressReference property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAddressReference(String value) {
        this.addressReference = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKey(String value) {
        this.key = value;
    }


}