//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-1.0.0.0_2-1-9-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.08 at 09:49:15 AM EST 
//


package dti.ci.entitymgr.impl.jdbchelpers;

import oracle.sql.ARRAY;
import oracle.sql.STRUCT;

import java.sql.*;


public class BasicAddressType implements SQLData {

    protected PrimaryIndicatorType primaryIndicator;
    protected PrimaryIndicatorType futurePrimaryIndicator;
    protected AddressTypeCodeType addressTypeCode;
    protected AddressPeriodType addressPeriod;
    protected String addressReference;
    protected com.delphi_tech.ows.party.BasicAddressType jaxbBasicAddressType;
    protected String key;

    public String sql_type;

    public String getSQLTypeName() throws SQLException {
          return sql_type;
    }

    public BasicAddressType(){
        jaxbBasicAddressType = new com.delphi_tech.ows.party.BasicAddressType();
    }

    public BasicAddressType(PrimaryIndicatorType primaryIndicator,
                            PrimaryIndicatorType futurePrimaryIndicator,
                            AddressTypeCodeType addressTypeCode,
                            AddressPeriodType addressPeriod,
                            String addressReference,
                            String key){
        jaxbBasicAddressType = new com.delphi_tech.ows.party.BasicAddressType();
        this.primaryIndicator = primaryIndicator;
        this.futurePrimaryIndicator = futurePrimaryIndicator;
        this.addressTypeCode = addressTypeCode;
        this.addressPeriod = addressPeriod;
        this.addressReference = addressReference;
        this.key = key;

        if(addressPeriod != null){
            jaxbBasicAddressType.setAddressPeriod(this.addressPeriod.getJaxbAddressPeriodType());
        }else{
            jaxbBasicAddressType.setAddressPeriod(new com.delphi_tech.ows.party.AddressPeriodType() );
        }
        if(primaryIndicator != null){
            jaxbBasicAddressType.setPrimaryIndicator(this.primaryIndicator.getJaxbPrimaryIndicatorType());
        }else{
             jaxbBasicAddressType.setPrimaryIndicator(new com.delphi_tech.ows.party.PrimaryIndicatorType());
        }
        if(futurePrimaryIndicator != null) {
            jaxbBasicAddressType.setFuturePrimaryIndicator(this.futurePrimaryIndicator.getJaxbFuturePrimaryIndicatorType());
        } else {
            jaxbBasicAddressType.setFuturePrimaryIndicator(new com.delphi_tech.ows.party.PrimaryIndicatorType());
        }
        if(addressPeriod != null){
            jaxbBasicAddressType.setAddressPeriod(this.addressPeriod.getJaxbAddressPeriodType());
        }else{
            jaxbBasicAddressType.setAddressPeriod( new com.delphi_tech.ows.party.AddressPeriodType());
        }
        if(addressReference != null ){
            jaxbBasicAddressType.setAddressReference(this.addressReference);
        }
        if(key != null ){
            jaxbBasicAddressType.setKey(this.key);
        }

    }
       public void readSQL(SQLInput stream,String typeName ) throws SQLException{
         sql_type = typeName;
         primaryIndicator = (PrimaryIndicatorType)setClass(stream.readObject(),PrimaryIndicatorType.class);
         addressTypeCode =  (AddressTypeCodeType) setClass(stream.readObject(),AddressTypeCodeType.class);
         addressPeriod =   (AddressPeriodType) setClass(stream.readObject(),AddressPeriodType.class);
         addressReference = stream.readString();
         key = stream.readString();

         if(addressTypeCode != null){
            jaxbBasicAddressType.setAddressTypeCode(addressTypeCode.getJaxbAddressTypeCodeType());
        }else{
            jaxbBasicAddressType.setAddressTypeCode(new com.delphi_tech.ows.party.AddressTypeCodeType() );
        }
        if(primaryIndicator != null){
            jaxbBasicAddressType.setPrimaryIndicator(this.primaryIndicator.getJaxbPrimaryIndicatorType());
            jaxbBasicAddressType.setFuturePrimaryIndicator(this.primaryIndicator.getJaxbFuturePrimaryIndicatorType());
        }else{
            jaxbBasicAddressType.setPrimaryIndicator(new com.delphi_tech.ows.party.PrimaryIndicatorType());
            jaxbBasicAddressType.setFuturePrimaryIndicator(new com.delphi_tech.ows.party.PrimaryIndicatorType());
        }
        if(addressPeriod != null){
            jaxbBasicAddressType.setAddressPeriod(this.addressPeriod.getJaxbAddressPeriodType());
        }else{
            jaxbBasicAddressType.setAddressPeriod( new com.delphi_tech.ows.party.AddressPeriodType());
        }

        jaxbBasicAddressType.setAddressReference((this.addressReference == null) ? "":addressReference);
        jaxbBasicAddressType.setKey((this.key == null) ? "":key);

     }
    public void writeSQL(SQLOutput stream) throws SQLException{
        /*
            This method should not have implementation
            We are not planning to make any updates using this method.
        */
     }
    public com.delphi_tech.ows.party.BasicAddressType getJaxbBasicAddressType(){
        return this.jaxbBasicAddressType;
    }

     private  Object setClass(Object obj, Class clazz){
        Object type=null;
       try{
        ARRAY tmp = (ARRAY)obj;
        ResultSet rs = tmp.getResultSet();
         while(rs.next()){
               STRUCT struct = (STRUCT) rs.getObject(2);
               type = struct.toClass(clazz);
           }
       }catch(Exception e){
           //do nothing  just return null
           e.getMessage();
       }
     return type;
    }
    /**
     * Gets the value of the primaryIndicator property.
     *
     * @return
     *     possible object is
     *     {@link dti.ci.entitymgr.impl.jdbchelpers.PrimaryIndicatorType }
     *
     */
    public PrimaryIndicatorType getPrimaryIndicator() {
        return primaryIndicator;
    }

    /**
     * Sets the value of the primaryIndicator property.
     *
     * @param value
     *     allowed object is
     *     {@link dti.ci.entitymgr.impl.jdbchelpers.PrimaryIndicatorType }
     *
     */
    public void setPrimaryIndicator(PrimaryIndicatorType value) {
        this.primaryIndicator = value;
    }

    /**
     * Gets the value of the addressTypeCode property.
     *
     * @return
     *     possible object is
     *     {@link AddressTypeCodeType }
     *
     */
    public AddressTypeCodeType getAddressTypeCode() {
        return addressTypeCode;
    }

    /**
     * Sets the value of the addressTypeCode property.
     *
     * @param value
     *     allowed object is
     *     {@link AddressTypeCodeType }
     *
     */
    public void setAddressTypeCode(AddressTypeCodeType value) {
        this.addressTypeCode = value;
    }

    /**
     * Gets the value of the addressPeriod property.
     *
     * @return
     *     possible object is
     *     {@link dti.ci.entitymgr.impl.jdbchelpers.AddressPeriodType }
     *
     */
    public AddressPeriodType getAddressPeriod() {
        return addressPeriod;
    }

    /**
     * Sets the value of the addressPeriod property.
     *
     * @param value
     *     allowed object is
     *     {@link dti.ci.entitymgr.impl.jdbchelpers.AddressPeriodType }
     *
     */
    public void setAddressPeriod(AddressPeriodType value) {
        this.addressPeriod = value;
    }

    /**
     * Gets the value of the addressReference property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAddressReference() {
        return addressReference;
    }

    /**
     * Sets the value of the addressReference property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAddressReference(String value) {
        this.addressReference = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKey(String value) {
        this.key = value;
    }

}