//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-1.0.0.0_2-1-9-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.08 at 09:49:15 AM EST 
//


package dti.ci.entitymgr.impl.jdbchelpers;

import com.delphi_tech.ows.common.MessageStatusType;

import java.sql.SQLData;
import java.sql.SQLException;
import java.sql.SQLInput;
import java.sql.SQLOutput;
import java.util.ArrayList;
import java.util.List;



public class PartyInquiryResultType  implements SQLData {

    protected String messageId;
    protected String correlationId;
    protected List<AddressType> address = new ArrayList();
    protected List<PersonType> person  = new ArrayList();
    protected List<OrganizationType> organization  = new ArrayList();
    protected List<PropertyType> property  = new ArrayList();
    protected List<PartyAdditionalInfoType> partyAdditionalInfo = new ArrayList<>();
    protected List<PartyAdditionalXmlInfoType> partyAdditionalXmlInfo = new ArrayList<>();
    protected MessageStatusType messageStatus;

    protected com.delphi_tech.ows.partyinquiryservice.PartyInquiryResultType  jaxbPartyInquiryResultType;

    public String sql_type;

    public String getSQLTypeName() throws SQLException {
          return sql_type;
    }

    public  PartyInquiryResultType(){
       jaxbPartyInquiryResultType = new com.delphi_tech.ows.partyinquiryservice.PartyInquiryResultType();
    }

    public com.delphi_tech.ows.partyinquiryservice.PartyInquiryResultType getJaxbPartyInquiryResultType(){
        return jaxbPartyInquiryResultType;
    }
    public PartyInquiryResultType(String messageId,String correlationId  ) {
         this.messageId  = messageId;
         this.correlationId = correlationId;
        jaxbPartyInquiryResultType = new com.delphi_tech.ows.partyinquiryservice.PartyInquiryResultType();

        jaxbPartyInquiryResultType.setCorrelationId(this.correlationId);
        jaxbPartyInquiryResultType.setMessageId(this.messageId);



    }

    public void readSQL(SQLInput stream,String typeName ) throws SQLException{
         sql_type = typeName;
         messageId = stream.readString();
         correlationId = stream.readString();
         jaxbPartyInquiryResultType.setCorrelationId((this.correlationId==null)?"":correlationId);
         jaxbPartyInquiryResultType.setMessageId((this.messageId==null)?"":messageId);
         jaxbPartyInquiryResultType.setMessageStatus(this.messageStatus);
     }
    public void writeSQL(SQLOutput stream) throws SQLException{
        /*
            This method should not have implementation
            We are not planning to make any updates using this method.
        */
     }

    /*
    Method to get empty JAXB PartResultType. The method wil bes if nothing returned from DB
    It will populate all the objects so all XML elements should appear as empty
     */
    public com.delphi_tech.ows.partyinquiryservice.PartyInquiryResultType getEmptyResult(){
      //PartyInquiryResultType result = new PartyInquiryResultType();
      AddressType addressType= new AddressType("","","","","","","",new StateOrProvinceCodeType("",""),"",
                                                new CountryCodeType("",""), "","",new PostOfficeAddressIndicatorType("",""),"", "");


      PersonType personType = new PersonType("","","","",
              new PersonNameType("","","","","","",""), "","","","","","","","","","","",
              new BusinessEmailType("",""),
              new BasicPhoneNumberType("",new PhoneTypeCodeType("",""),"",
                            new PrimaryIndicatorType("",""),"",""),
              new BasicAddressType(new PrimaryIndicatorType("",""), new PrimaryIndicatorType("", ""),
                        new AddressTypeCodeType("",""),new AddressPeriodType("",""),"",""),
              new EducationInformationType("","","","","",
                                    new EducationalInstitutionType("","","",new StateOrProvinceCodeType("",""))),
              new ProfessionalLicenseType("","","",new LicensePeriodType("",""),
                        new StateOrProvinceCodeType("",""),
                        new SuspReinstInformationType(
                                new LicenseSuspensionPeriodType("",""),"")),
              new CertificationType("","","","", new CertificationPeriodType("",""),"","",
                                new CtlStateOrProvinceCodeType("","")),
             new ContactType("","", new PersonNameType("","","","","","",""),new BusinessEmailType("",""),
                         new BasicPhoneNumberType("", new PhoneTypeCodeType("",""),"", new PrimaryIndicatorType("",""),"","")),
              new PartyNoteType("","","","","",""),
              new RelationshipType("", "", "", new EffectivePeriodType("", ""), new ReferredPartyType("", "", ""), "", ""),
              new PartyClassificationType("", "", "", "", "", new EffectivePeriodType("", ""))
              );

        OrganizationType organizationType = new OrganizationType("", "", "", "", "", new OrganizationNameType(""),"","","","","","","",
                new BusinessEmailType("", ""), new BasicPhoneNumberType("", new PhoneTypeCodeType("", ""), "", new PrimaryIndicatorType("", ""), "", ""),
                new BasicAddressType(new PrimaryIndicatorType("", ""), new PrimaryIndicatorType("", ""), new AddressTypeCodeType("", ""), new AddressPeriodType("", ""), "", ""),
                new OrganizationLicenseType("", "", "", new LicensePeriodType("", ""),
                        new StateOrProvinceCodeType("", ""),
                        new SuspReinstInformationType(
                                new LicenseSuspensionPeriodType("", ""), "")),
                new CertificationType("", "", "", "", new CertificationPeriodType("", ""), "", "",
                        new CtlStateOrProvinceCodeType("", "")), new PartyNoteType("","","","","",""),
                new RelationshipType("", "", "", new EffectivePeriodType("", ""), new ReferredPartyType("", "", ""), "", ""),
                new PartyClassificationType("", "", "", "", "", new EffectivePeriodType("", "")));

      PropertyType propertyType = new PropertyType("","",new PropertyNameType(""),
              new BasicPhoneNumberType("", new PhoneTypeCodeType("",""),"", new PrimaryIndicatorType("",""),"",""),
              new BasicAddressType(new PrimaryIndicatorType("",""), new PrimaryIndicatorType("", ""),
                        new AddressTypeCodeType("",""),new AddressPeriodType("",""),"","")
        );

        PartyAdditionalInfoType partyAdditionalInfoType = new PartyAdditionalInfoType(
                new PersonAdditionalInfoType("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""),
                new OrganizationAdditionalInfoType("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""),
                new AddressAdditionalInfoType("", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "")
        );

        PartyAdditionalXmlInfoType partyAdditionalXmlInfoType = new PartyAdditionalXmlInfoType(
                new EntityAdditionalXmlDataType("", "", ""),
                new AddressAdditionalXmlDataType("", "")
        );

      jaxbPartyInquiryResultType.getAddress().add(addressType.getJaxbAddressType());
      jaxbPartyInquiryResultType.getPerson().add(personType.getJaxbPersonType());
      jaxbPartyInquiryResultType.getOrganization().add(organizationType.jaxbOrganizationType);
      jaxbPartyInquiryResultType.getProperty().add(propertyType.getJaxbPropertyType());
      jaxbPartyInquiryResultType.setPartyAdditionalInfo(partyAdditionalInfoType.jaxbPartyAdditionalInfoType);
      jaxbPartyInquiryResultType.setPartyAdditionalXmlInfo(partyAdditionalXmlInfoType.jaxbPartyAdditionalXmlInfoType);

      return jaxbPartyInquiryResultType;
    }
    /**
     * Gets the value of the messageId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMessageId(String value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the correlationId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * Sets the value of the correlationId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCorrelationId(String value) {
        this.correlationId = value;
    }

    /**
     * Gets the value of the address property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.delphi_tech.ows.party.AddressType }
     *
     *
     */
    public List<AddressType> getAddress() {
        if (address == null) {
            address = new ArrayList<AddressType>();
        }
        return this.address;
    }

    /**
     * Gets the value of the person property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the person property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerson().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.delphi_tech.ows.party.PersonType }
     *
     *
     */
    public List<PersonType> getPerson() {
        if (person == null) {
            person = new ArrayList<PersonType>();
        }
        return this.person;
    }

    /**
     * Gets the value of the organization property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organization property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganization().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.delphi_tech.ows.party.OrganizationType }
     *
     *
     */
    public List<OrganizationType> getOrganization() {
        if (organization == null) {
            organization = new ArrayList<OrganizationType>();
        }
        return this.organization;
    }

    /**
     * Gets the value of the property property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.delphi_tech.ows.party.PropertyType }
     *
     *
     */
    public List<PropertyType> getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyType>();
        }
        return this.property;
    }

    public List<PartyAdditionalInfoType> getPartyAdditionalInfo() {
        if (partyAdditionalInfo == null) {
            partyAdditionalInfo = new ArrayList<PartyAdditionalInfoType>();
        }
        return partyAdditionalInfo;
    }

    public List<PartyAdditionalXmlInfoType> getPartyAdditionalXmlInfo() {
        if (partyAdditionalXmlInfo == null) {
            partyAdditionalXmlInfo = new ArrayList<PartyAdditionalXmlInfoType>();
        }
        return partyAdditionalXmlInfo;
    }

    /**
     * Gets the value of the messageStatus property.
     *
     * @return
     *     possible object is
     *     {@link com.delphi_tech.ows.common.MessageStatusType }
     *
     */
    public MessageStatusType getMessageStatus() {
        return messageStatus;
    }

    /**
     * Sets the value of the messageStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link com.delphi_tech.ows.common.MessageStatusType }
     *
     */
    public void setMessageStatus(MessageStatusType value) {
        this.messageStatus = value;
    }

    public void addAddress(AddressType address){
        this.address.add( address);
        jaxbPartyInquiryResultType.getAddress().add(address.getJaxbAddressType());
    }
    public void addPerson(PersonType person){
        this.person.add(person);
        jaxbPartyInquiryResultType.getPerson().add(person.getJaxbPersonType());
    }
    public void addOrganization(OrganizationType organization){
        this.organization.add(organization);
        jaxbPartyInquiryResultType.getOrganization().add(organization.getJaxbOrganizationType());
    }

    public void addProperty(PropertyType property){
        this.property.add(property);
        jaxbPartyInquiryResultType.getProperty().add(property.getJaxbPropertyType());
    }

    public void addPartyAdditionalInfo(PartyAdditionalInfoType partyAdditionalInfo) {
        this.partyAdditionalInfo.add(partyAdditionalInfo);

        if (partyAdditionalInfo != null) {
            if (partyAdditionalInfo.getPersonAdditionalInfo() != null) {
                for (PersonAdditionalInfoType personAdditionalInfo : partyAdditionalInfo.getPersonAdditionalInfo()) {
                    if (jaxbPartyInquiryResultType.getPartyAdditionalInfo() == null) {
                        jaxbPartyInquiryResultType.setPartyAdditionalInfo(new com.delphi_tech.ows.party.PartyAdditionalInfoType());
                    }

                    jaxbPartyInquiryResultType.getPartyAdditionalInfo().getPersonAdditionalInfo().add(personAdditionalInfo.getJaxbPersonAdditionalInfoType());
                }

                for (OrganizationAdditionalInfoType organizationAdditionalInfoType : partyAdditionalInfo.getOrganizationAdditionalInfo()) {
                    if (jaxbPartyInquiryResultType.getPartyAdditionalInfo() == null) {
                        jaxbPartyInquiryResultType.setPartyAdditionalInfo(new com.delphi_tech.ows.party.PartyAdditionalInfoType());
                    }

                    jaxbPartyInquiryResultType.getPartyAdditionalInfo().getOrganizationAdditionalInfo().add(organizationAdditionalInfoType.getJaxbOrganizationAdditionalInfoType());
                }

                for (AddressAdditionalInfoType addressAdditionalInfoType : partyAdditionalInfo.getAddressAdditionalInfo()) {
                    if (jaxbPartyInquiryResultType.getPartyAdditionalInfo() == null) {
                        jaxbPartyInquiryResultType.setPartyAdditionalInfo(new com.delphi_tech.ows.party.PartyAdditionalInfoType());
                    }

                    jaxbPartyInquiryResultType.getPartyAdditionalInfo().getAddressAdditionalInfo().add(addressAdditionalInfoType.getJaxbAddressAdditionalInfoType());
                }
            }
        }
    }

    public void addPartyAdditionalXmlInfo(PartyAdditionalXmlInfoType partyAdditionalXmlInfoType) {
        this.partyAdditionalXmlInfo.add(partyAdditionalXmlInfoType);

        if (partyAdditionalXmlInfoType != null) {
            if (partyAdditionalXmlInfoType.getEntityAdditionalXmlData() != null) {
                for (EntityAdditionalXmlDataType entityAdditionalXmlDataType : partyAdditionalXmlInfoType.getEntityAdditionalXmlData()) {
                    if (jaxbPartyInquiryResultType.getPartyAdditionalXmlInfo() == null) {
                        jaxbPartyInquiryResultType.setPartyAdditionalXmlInfo(new com.delphi_tech.ows.party.PartyAdditionalXmlInfoType());
                    }

                    jaxbPartyInquiryResultType.getPartyAdditionalXmlInfo().getEntityAdditionalXmlData().add(entityAdditionalXmlDataType.getJaxbEntityAdditionalXmlDataType());
                }

                for (AddressAdditionalXmlDataType organizationAdditionalInfoType : partyAdditionalXmlInfoType.getAddressAdditionalXmlData()) {
                    if (jaxbPartyInquiryResultType.getPartyAdditionalXmlInfo() == null) {
                        jaxbPartyInquiryResultType.setPartyAdditionalXmlInfo(new com.delphi_tech.ows.party.PartyAdditionalXmlInfoType());
                    }

                    jaxbPartyInquiryResultType.getPartyAdditionalXmlInfo().getAddressAdditionalXmlData().add(organizationAdditionalInfoType.getJaxbAddressAdditionalXmlDataType());
                }
            }
        }
    }
}
