//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-1.0.0.0_2-1-9-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.08 at 09:49:15 AM EST 
//


package dti.ci.entitymgr.impl.jdbchelpers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.sql.SQLData;
import java.sql.SQLException;
import java.sql.SQLInput;
import java.sql.SQLOutput;


public class PersonNameType implements SQLData {

    protected String surname;
    protected String givenName;
    protected String otherGivenName;
    protected String personTitlePrefix;
    protected String nameSuffix;
    protected String fullName;
    protected String personTitle;
    protected com.delphi_tech.ows.party.PersonNameType jaxbPersonNameType;


    public String sql_type;

    public String getSQLTypeName() throws SQLException {
          return sql_type;
    }

    public  PersonNameType(){
        jaxbPersonNameType = new com.delphi_tech.ows.party.PersonNameType();
    }

    public PersonNameType(String surname,String givenName, String otherGivenName, String personTitlePrefix,
                          String nameSuffix,String fullName, String personTitle){
        this.surname = surname;
        this.givenName = givenName;
        this.otherGivenName = otherGivenName;
        this.personTitlePrefix =personTitlePrefix;
        this.nameSuffix = nameSuffix;
        this.fullName = fullName;
        this.personTitle = personTitle;

        jaxbPersonNameType = new com.delphi_tech.ows.party.PersonNameType();
        jaxbPersonNameType.setFullName(this.fullName);
        jaxbPersonNameType.setGivenName(this.givenName);
        jaxbPersonNameType.setOtherGivenName(this.otherGivenName);
        jaxbPersonNameType.setPersonTitlePrefix(this.personTitlePrefix);
        jaxbPersonNameType.setNameSuffix(this.nameSuffix);
        jaxbPersonNameType.setPersonTitle(this.personTitle);

    }

    public void readSQL(SQLInput stream,String typeName ) throws SQLException{
         sql_type = typeName;
         surname = stream.readString();
         givenName = stream.readString();
         otherGivenName = stream.readString();
         personTitlePrefix = stream.readString();
         nameSuffix   = stream.readString();
         fullName       = stream.readString();
        personTitle = stream.readString();

        jaxbPersonNameType = new com.delphi_tech.ows.party.PersonNameType();
        jaxbPersonNameType.setSurname((this.surname==null)?"":surname);
        jaxbPersonNameType.setFullName((this.fullName==null)?"":fullName);
        jaxbPersonNameType.setGivenName((this.givenName==null)?"":givenName);
        jaxbPersonNameType.setOtherGivenName((this.otherGivenName==null)?"":otherGivenName);
        jaxbPersonNameType.setPersonTitlePrefix((this.personTitlePrefix==null)?"":personTitlePrefix);
        jaxbPersonNameType.setNameSuffix((this.nameSuffix==null)?"":nameSuffix);
        jaxbPersonNameType.setPersonTitle((this.personTitle==null)?"":personTitle);

     }
    public void writeSQL(SQLOutput stream) throws SQLException{
        /*
            This method should not have implementation
            We are not planning to make any updates using this method.
        */
     }


    public com.delphi_tech.ows.party.PersonNameType getJaxbPersonNameType(){
       return jaxbPersonNameType;
    }
    /**
     * Gets the value of the surname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the givenName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGivenName() {
        return givenName;
    }

    /**
     * Sets the value of the givenName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGivenName(String value) {
        this.givenName = value;
    }

    /**
     * Gets the value of the otherGivenName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOtherGivenName() {
        return otherGivenName;
    }

    /**
     * Sets the value of the otherGivenName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOtherGivenName(String value) {
        this.otherGivenName = value;
    }

    /**
     * Gets the value of the personTitlePrefix property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPersonTitlePrefix() {
        return personTitlePrefix;
    }

    /**
     * Sets the value of the personTitlePrefix property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPersonTitlePrefix(String value) {
        this.personTitlePrefix = value;
    }

    /**
     * Gets the value of the nameSuffix property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNameSuffix() {
        return nameSuffix;
    }

    /**
     * Sets the value of the nameSuffix property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNameSuffix(String value) {
        this.nameSuffix = value;
    }

    /**
     * Gets the value of the fullName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    public String getPersonTitle() {
        return personTitle;
    }

    public void setPersonTitle(String personTitle) {
        this.personTitle = personTitle;
    }
}
