//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-1.0.0.0_2-1-9-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.08 at 09:49:15 AM EST 
//


package dti.ci.entitymgr.impl.jdbchelpers;

import oracle.sql.ARRAY;
import oracle.sql.Datum;
import oracle.sql.STRUCT;

import javax.xml.bind.annotation.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
public class PropertyType implements SQLData {

    protected String propertyNumberId;
    protected String key;
    protected PropertyNameType propertyName;
    protected List<BasicPhoneNumberType> basicPhoneNumber;
    protected BasicAddressType basicAddress;

    protected com.delphi_tech.ows.party.PropertyType jaxbPropertyType;

    public String sql_type;

    public String getSQLTypeName() throws SQLException {
          return sql_type;
    }

    public PropertyType(){
        jaxbPropertyType = new com.delphi_tech.ows.party.PropertyType();
    }

    public PropertyType(String propertyNumberId,String key,
                        PropertyNameType propertyName,
                        BasicPhoneNumberType basicPhoneNumber,
                        BasicAddressType basicAddress){
       this.propertyNumberId = propertyNumberId;
       this.key = key;
       this.propertyName = propertyName;
       this.getBasicPhoneNumber().add(basicPhoneNumber);
       this.basicAddress = basicAddress;

        jaxbPropertyType = new com.delphi_tech.ows.party.PropertyType();
       jaxbPropertyType.setPropertyNumberId(this.propertyNumberId);
        jaxbPropertyType.setKey(this.key);
        jaxbPropertyType.setPropertyName(this.propertyName.getJaxbPropertyNameType());
        jaxbPropertyType.setBasicAddress(this.basicAddress.getJaxbBasicAddressType());
        jaxbPropertyType.getBasicPhoneNumber().add(basicPhoneNumber.getJaxbBasicPhoneNumberType());
    }

    public void readSQL(SQLInput stream,String typeName ) throws SQLException{
         sql_type = typeName;
         propertyNumberId = stream.readString();
         key = stream.readString();
         propertyName= (PropertyNameType)setClass(stream.readObject(), PropertyNameType.class);
         basicPhoneNumber= (List) setList(stream.readObject(),BasicPhoneNumberType.class );
         basicAddress = (BasicAddressType)setClass(stream.readObject(), BasicAddressType.class);

        jaxbPropertyType.setPropertyNumberId(this.propertyNumberId);
         jaxbPropertyType.setKey(this.key);
         if(propertyName != null){
            jaxbPropertyType.setPropertyName(this.propertyName.getJaxbPropertyNameType());
         }else{
            jaxbPropertyType.setPropertyName(new com.delphi_tech.ows.party.PropertyNameType());
         }
         if(basicAddress != null){
            jaxbPropertyType.setBasicAddress(this.basicAddress.getJaxbBasicAddressType());
         }else{
            jaxbPropertyType.setBasicAddress(new com.delphi_tech.ows.party.BasicAddressType());
         }

        Iterator it = basicPhoneNumber.iterator();
        while (it.hasNext()) {
            com.delphi_tech.ows.party.BasicPhoneNumberType phone = ((BasicPhoneNumberType) it.next()).getJaxbBasicPhoneNumberType();
            if (jaxbPropertyType.getBasicAddress().getAddressReference().equalsIgnoreCase(phone.getAddressReference())) {
                jaxbPropertyType.getBasicPhoneNumber().add(phone);
            }
        }
        if (jaxbPropertyType.getBasicPhoneNumber() == null) {
            jaxbPropertyType.getBasicPhoneNumber().add(new com.delphi_tech.ows.party.BasicPhoneNumberType());
        }

     }
    public void writeSQL(SQLOutput stream) throws SQLException{
        /*
            This method should not have implementation
            We are not planning to make any updates using this method.
        */
     }

    private  Object setClass(Object obj, Class clazz){
        Object type=null;
       try{
        ARRAY tmp = (ARRAY)obj;
        ResultSet rs = tmp.getResultSet();
         while(rs.next()){
               STRUCT struct = (STRUCT) rs.getObject(2);
               type = struct.toClass(clazz);
           }
       }catch(Exception e){
           //do nothing  just return null
           e.getMessage();
       }
     return type;
    }
    private List setList(Object obj, Class clazz){
        List lst = new ArrayList();
        try{
            Object resultElems = ((ARRAY)obj).getOracleArray();
            Datum[] listElems = (Datum[]) resultElems;
            for(int r=0;r<listElems.length;r++){
                STRUCT struct = (STRUCT) listElems[r];
                lst.add( struct.toClass(clazz));
            }

        }catch(Exception e){
            // do nothing just return null
           e.getMessage();
        }
      return lst;
    }

    public  com.delphi_tech.ows.party.PropertyType getJaxbPropertyType(){
        return jaxbPropertyType;
    }
    public void addBasicPhoneNumberType(BasicPhoneNumberType type){
        this.getBasicPhoneNumber().add(type);
        jaxbPropertyType.getBasicPhoneNumber().add(type.getJaxbBasicPhoneNumberType());
    }
    /**
     * Gets the value of the propertyNumberId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPropertyNumberId() {
        return propertyNumberId;
    }

    /**
     * Sets the value of the propertyNumberId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPropertyNumberId(String value) {
        this.propertyNumberId = value;
    }

    /**
     * Gets the value of the propertyName property.
     *
     * @return
     *     possible object is
     *     {@link PropertyNameType }
     *
     */
    public PropertyNameType getPropertyName() {
        return propertyName;
    }

    /**
     * Sets the value of the propertyName property.
     *
     * @param value
     *     allowed object is
     *     {@link PropertyNameType }
     *
     */
    public void setPropertyName(PropertyNameType value) {
        this.propertyName = value;
    }

    /**
     * Gets the value of the basicPhoneNumber property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the basicPhoneNumber property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBasicPhoneNumber().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BasicPhoneNumberType }
     *
     *
     */
    public List<BasicPhoneNumberType> getBasicPhoneNumber() {
        if (basicPhoneNumber == null) {
            basicPhoneNumber = new ArrayList<BasicPhoneNumberType>();
        }
        return this.basicPhoneNumber;
    }

    /**
     * Gets the value of the basicAddress property.
     *
     * @return
     *     possible object is
     *     {@link BasicAddressType }
     *
     */
    public BasicAddressType getBasicAddress() {
        return basicAddress;
    }

    /**
     * Sets the value of the basicAddress property.
     *
     * @param value
     *     allowed object is
     *     {@link BasicAddressType }
     *
     */
    public void setBasicAddress(BasicAddressType value) {
        this.basicAddress = value;
    }

    /**
     * Gets the value of the key property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKey(String value) {
        this.key = value;
    }

}