@echo off
rem runinst.bat log installation run
rem 061014 scf created
rem usage: runinst install.sql
if exist runinst.log del runinst.log
if not exist runinst.log echo runinst.log generated by runinst.bat version 061018 dti>runinst.log
echo ----------------------------------------------------->>runinst.log
echo %1 run on %date% at %time:~0,5% by %username%>>runinst.log
echo install.sql: %1>>runinst.log
echo date: %date%>>runinst.log
echo time: %time%>>runinst.log
echo operator: %username%>>runinst.log
echo directory: %cd%>>runinst.log
echo path: %path%>>runinst.log
echo environment:>>runinst.log
set>>runinst.log
echo ----------------------------------------------------->>runinst.log
echo P4 sessions per user>>runinst.log
p4 tickets >>runinst.log
echo ----------------------------------------------------->>runinst.log
echo P4 connection information>>runinst.log
p4 info >>runinst.log
echo ----------------------------------------------------->>runinst.log