
package com.delphi_tech.ows.policynumbergenerationservice;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PolicyNumberGenerationService", targetNamespace = "http://www.delphi-tech.com/ows/PolicyNumberGenerationService", wsdlLocation = "PolicyNumberGenerationService.wsdl")
public class PolicyNumberGenerationService_Service
    extends Service
{

    private final static URL POLICYNUMBERGENERATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException POLICYNUMBERGENERATIONSERVICE_EXCEPTION;
    private final static QName POLICYNUMBERGENERATIONSERVICE_QNAME = new QName("http://www.delphi-tech.com/ows/PolicyNumberGenerationService", "PolicyNumberGenerationService");

    static {
        POLICYNUMBERGENERATIONSERVICE_WSDL_LOCATION = PolicyNumberGenerationService_Service.class.getResource("PolicyNumberGenerationService.wsdl");
        WebServiceException e = null;
        if (POLICYNUMBERGENERATIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'PolicyNumberGenerationService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        POLICYNUMBERGENERATIONSERVICE_EXCEPTION = e;
    }

    public PolicyNumberGenerationService_Service() {
        super(__getWsdlLocation(), POLICYNUMBERGENERATIONSERVICE_QNAME);
    }

    public PolicyNumberGenerationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), POLICYNUMBERGENERATIONSERVICE_QNAME, features);
    }

    public PolicyNumberGenerationService_Service(URL wsdlLocation) {
        super(wsdlLocation, POLICYNUMBERGENERATIONSERVICE_QNAME);
    }

    public PolicyNumberGenerationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POLICYNUMBERGENERATIONSERVICE_QNAME, features);
    }

    public PolicyNumberGenerationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyNumberGenerationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PolicyNumberGenerationService
     */
    @WebEndpoint(name = "PolicyNumberGenerationServicePort")
    public PolicyNumberGenerationService getPolicyNumberGenerationServicePort() {
        return super.getPort(new QName("http://www.delphi-tech.com/ows/PolicyNumberGenerationService", "PolicyNumberGenerationServicePort"), PolicyNumberGenerationService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolicyNumberGenerationService
     */
    @WebEndpoint(name = "PolicyNumberGenerationServicePort")
    public PolicyNumberGenerationService getPolicyNumberGenerationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.delphi-tech.com/ows/PolicyNumberGenerationService", "PolicyNumberGenerationServicePort"), PolicyNumberGenerationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POLICYNUMBERGENERATIONSERVICE_EXCEPTION!= null) {
            throw POLICYNUMBERGENERATIONSERVICE_EXCEPTION;
        }
        return POLICYNUMBERGENERATIONSERVICE_WSDL_LOCATION;
    }

}
