
package com.delphi_tech.ows.policyinquiryservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PolicyInquiryService", targetNamespace = "http://www.delphi-tech.com/ows/PolicyInquiryService", wsdlLocation = "PolicyInquiryService.wsdl")
public class PolicyInquiryService_Service
    extends Service
{

    private final static URL POLICYINQUIRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException POLICYINQUIRYSERVICE_EXCEPTION;
    private final static QName POLICYINQUIRYSERVICE_QNAME = new QName("http://www.delphi-tech.com/ows/PolicyInquiryService", "PolicyInquiryService");

    static {
        POLICYINQUIRYSERVICE_WSDL_LOCATION = com.delphi_tech.ows.policyinquiryservice.PolicyInquiryService_Service.class.getResource("PolicyInquiryService.wsdl");
        WebServiceException e = null;
        if (POLICYINQUIRYSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'PolicyInquiryService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        POLICYINQUIRYSERVICE_EXCEPTION = e;
    }

    public PolicyInquiryService_Service() {
        super(__getWsdlLocation(), POLICYINQUIRYSERVICE_QNAME);
    }

    public PolicyInquiryService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), POLICYINQUIRYSERVICE_QNAME, features);
    }

    public PolicyInquiryService_Service(URL wsdlLocation) {
        super(wsdlLocation, POLICYINQUIRYSERVICE_QNAME);
    }

    public PolicyInquiryService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POLICYINQUIRYSERVICE_QNAME, features);
    }

    public PolicyInquiryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyInquiryService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PolicyInquiryService
     */
    @WebEndpoint(name = "PolicyInquiryServicePort")
    public PolicyInquiryService getPolicyInquiryServicePort() {
        return super.getPort(new QName("http://www.delphi-tech.com/ows/PolicyInquiryService", "PolicyInquiryServicePort"), PolicyInquiryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolicyInquiryService
     */
    @WebEndpoint(name = "PolicyInquiryServicePort")
    public PolicyInquiryService getPolicyInquiryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.delphi-tech.com/ows/PolicyInquiryService", "PolicyInquiryServicePort"), PolicyInquiryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POLICYINQUIRYSERVICE_EXCEPTION!= null) {
            throw POLICYINQUIRYSERVICE_EXCEPTION;
        }
        return POLICYINQUIRYSERVICE_WSDL_LOCATION;
    }

}
