
package com.delphi_tech.ows.policyinquiryservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PolicyInquiryService", targetNamespace = "http://www.delphi-tech.com/ows/PolicyInquiryService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.delphi_tech.ows.account.ObjectFactory.class,
    com.delphi_tech.ows.common.ObjectFactory.class,
    com.delphi_tech.ows.party.ObjectFactory.class,
    com.delphi_tech.ows.policy.ObjectFactory.class,
    com.delphi_tech.ows.policyinquiryservice.ObjectFactory.class
})
public interface PolicyInquiryService {


    /**
     * 
     * @param policyInquiryRequest
     * @return
     *     returns com.delphi_tech.ows.policyinquiryservice.PolicyInquiryResultType
     */
    @WebMethod(action = "policyInquiryRequest")
    @WebResult(name = "PolicyInquiryResult", targetNamespace = "http://www.delphi-tech.com/ows/PolicyInquiryService", partName = "policyInquiryResult")
    public PolicyInquiryResultType policyInquiryRequest(
        @WebParam(name = "PolicyInquiryRequest", targetNamespace = "http://www.delphi-tech.com/ows/PolicyInquiryService", partName = "policyInquiryRequest")
        PolicyInquiryRequestType policyInquiryRequest);

}
