INSERT INTO OS_FORM_INTERFACE_CONFIG (OS_FORM_INTERFACE_CONFIG_PK, DOC_GEN_PRD_NAME, CATEGORY, SUB_CATEGORY, CODE, DESCRIPTION, VALUE)
SELECT OASIS_SEQUENCE.NEXTVAL, 'ELOQUENCE', 'GENERAL', 'GENERAL', 'IS_EXCLUDE_NULL_VALUE_FIELDS_IN_XML' , 
       'A TRUE/FALSE value that indicates whether to export NULL value fields or not. Default value is TRUE.', 'FALSE'
  FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM OS_FORM_INTERFACE_CONFIG
                    WHERE DOC_GEN_PRD_NAME = 'ELOQUENCE'
                      AND CATEGORY = 'GENERAL'
                      AND SUB_CATEGORY = 'GENERAL'
                      AND CODE = 'IS_EXCLUDE_NULL_VALUE_FIELDS_IN_XML');

--INSERT INTO BUILD_APPLIED(owner, build_id, timestamp) VALUES (user, 'Fix for 192489', sysdate);

