
package com.delphi_tech.ows.policyCertificateOfInsuranceChangeService;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "PolicyCertificateOfInsuranceChangeService", targetNamespace = "http://www.delphi-tech.com/ows/PolicyCertificateOfInsuranceChangeService", wsdlLocation = "PolicyCertificateOfInsuranceChangeService.wsdl")
public class PolicyCertificateOfInsuranceChangeService_Service
    extends Service
{

    private final static URL POLICYCERTIFICATEOFINSURANCECHANGESERVICE_WSDL_LOCATION;
    private final static WebServiceException POLICYCERTIFICATEOFINSURANCECHANGESERVICE_EXCEPTION;
    private final static QName POLICYCERTIFICATEOFINSURANCECHANGESERVICE_QNAME = new QName("http://www.delphi-tech.com/ows/PolicyCertificateOfInsuranceChangeService", "PolicyCertificateOfInsuranceChangeService");

    static {
        POLICYCERTIFICATEOFINSURANCECHANGESERVICE_WSDL_LOCATION = PolicyCertificateOfInsuranceChangeService_Service.class.getResource("PolicyCertificateOfInsuranceChangeService.wsdl");
        WebServiceException e = null;
        if (POLICYCERTIFICATEOFINSURANCECHANGESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'PolicyCertificateOfInsuranceChangeService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        POLICYCERTIFICATEOFINSURANCECHANGESERVICE_EXCEPTION = e;
    }

    public PolicyCertificateOfInsuranceChangeService_Service() {
        super(__getWsdlLocation(), POLICYCERTIFICATEOFINSURANCECHANGESERVICE_QNAME);
    }

    public PolicyCertificateOfInsuranceChangeService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), POLICYCERTIFICATEOFINSURANCECHANGESERVICE_QNAME, features);
    }

    public PolicyCertificateOfInsuranceChangeService_Service(URL wsdlLocation) {
        super(wsdlLocation, POLICYCERTIFICATEOFINSURANCECHANGESERVICE_QNAME);
    }

    public PolicyCertificateOfInsuranceChangeService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POLICYCERTIFICATEOFINSURANCECHANGESERVICE_QNAME, features);
    }

    public PolicyCertificateOfInsuranceChangeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyCertificateOfInsuranceChangeService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PolicyCertificateOfInsuranceChangeService
     */
    @WebEndpoint(name = "PolicyCertificateOfInsuranceChangeServicePort")
    public PolicyCertificateOfInsuranceChangeService getPolicyCertificateOfInsuranceChangeServicePort() {
        return super.getPort(new QName("http://www.delphi-tech.com/ows/PolicyCertificateOfInsuranceChangeService", "PolicyCertificateOfInsuranceChangeServicePort"), PolicyCertificateOfInsuranceChangeService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolicyCertificateOfInsuranceChangeService
     */
    @WebEndpoint(name = "PolicyCertificateOfInsuranceChangeServicePort")
    public PolicyCertificateOfInsuranceChangeService getPolicyCertificateOfInsuranceChangeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.delphi-tech.com/ows/PolicyCertificateOfInsuranceChangeService", "PolicyCertificateOfInsuranceChangeServicePort"), PolicyCertificateOfInsuranceChangeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POLICYCERTIFICATEOFINSURANCECHANGESERVICE_EXCEPTION!= null) {
            throw POLICYCERTIFICATEOFINSURANCECHANGESERVICE_EXCEPTION;
        }
        return POLICYCERTIFICATEOFINSURANCECHANGESERVICE_WSDL_LOCATION;
    }
}
