package com.delphi_tech.ows.policyCertificateOfInsuranceChangeService;

import com.delphi_tech.ows.policycertificateofinsurancechangeservice.MedicalMalpracticeCertificateOfLiabilityChangeRequestType;
import com.delphi_tech.ows.policycertificateofinsurancechangeservice.MedicalMalpracticeCertificateOfLiabilityChangeResultType;
import com.delphi_tech.ows.policycertificateofinsurancechangeservice.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 *
 */
@WebService(name = "PolicyCertificateOfInsuranceChangeService", targetNamespace = "http://www.delphi-tech.com/ows/PolicyCertificateOfInsuranceChangeService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.delphi_tech.ows.common.ObjectFactory.class,
    ObjectFactory.class
})
public interface PolicyCertificateOfInsuranceChangeService {

    /**
     *
     * @param medicalMalpracticeCertificateOfLiabilityChangeRequest
     * @return
     *     returns com.delphi_tech.ows.PolicyCertificateOfInsuranceChangeService.MedicalMalpracticeCertificateOfLiabilityChangeResultType
     */
    @WebMethod(action = "generateCoi")
    @WebResult(name = "MedicalMalpracticeCertificateOfLiabilityChangeResult", targetNamespace = "http://www.delphi-tech.com/ows/PolicyCertificateOfInsuranceChangeService", partName = "MedicalMalpracticeCertificateOfLiabilityChangeResult")
    public MedicalMalpracticeCertificateOfLiabilityChangeResultType generateCoi(
        @WebParam(name = "MedicalMalpracticeCertificateOfLiabilityChangeRequest", targetNamespace = "http://www.delphi-tech.com/ows/PolicyCertificateOfInsuranceChangeService", partName = "MedicalMalpracticeCertificateOfLiabilityChangeRequest")
            MedicalMalpracticeCertificateOfLiabilityChangeRequestType medicalMalpracticeCertificateOfLiabilityChangeRequest);
}
